name: Master Deployment
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build golang binary
      run: make build
    - name: Running code tests
      run: make test
      
#    - name: Logging in to container registry
#      env:
#        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
#        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#      run: |
#        echo $DOCKER_PASSWORD >> ~/pass.txt
#        cat ~/pass.txt | docker login --username $DOCKER_USERNAME --password-stdin
#    - name: Build docker image
#      run: make docker
#    - name: Publish docker image
#      run: make docker-publish




    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
          images: iberejr/nsx_exporter

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

